### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by IllusionTheDev**
Code Cleanup for the bukkit version

### CODE REVIEW

**Comment by x9nico** [comment]
Hello @IllusionTheDev thanks for your PR.
Can you fix in Bukkit Class your error please ? You set a TextComponent in sendMessage().
Once you have fixed that, I merge.

**Comment by IllusionTheDev** [comment]
The TextComponent is part of the bungee class, 
image
image

**Comment by x9nico** [comment]
Oh, yes, sorry.
I will merge Tomorrow.

**Comment by x9nico** [comment]
It doesn't send the message on join.

**Pull request closed without merging**
